# Dockerfile.test
FROM python:3.11

WORKDIR /app

# Устанавливаем git, т.к. он может быть нужен для установки зависимостей
RUN apt-get update && apt-get install -y git libpq-dev build-essential && rm -rf /var/lib/apt/lists/*

# Создаем файл для тестовых зависимостей
COPY requirements.txt .
# Установим основные зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем и устанавливаем зависимости для разработки/тестирования
# (Создайте этот файл и добавьте в него pytest, httpx)
COPY requirements.dev.txt .
RUN pip install --no-cache-dir -r requirements.dev.txt

# Копируем весь код проекта в контейнер
COPY . .
